import type { DictionaryEntry } from '../types';

export const dictionaryEntries: DictionaryEntry[] = [
  {
    id: 'alphabet-a-bisindo',
    word: 'A',
    category: 'alfabet',
    type: 'bisindo',
    description: 'Tangan dominan membentuk huruf A dengan kepalan lembut dan ibu jari di sisi telunjuk.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'alphabet-b-bisindo',
    word: 'B',
    category: 'alfabet',
    type: 'bisindo',
    description: 'Telapak tangan terbuka tegak dengan jari-jari rapat dan ibu jari menekuk ke depan telapak.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'alphabet-c-bisindo',
    word: 'C',
    category: 'alfabet',
    type: 'bisindo',
    description: 'Jari-jari dan ibu jari melengkung membentuk setengah lingkaran seperti huruf C.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'alphabet-d-bisindo',
    word: 'D',
    category: 'alfabet',
    type: 'bisindo',
    description: 'Telunjuk tegak lurus, jari lain bertemu ibu jari membentuk lingkaran kecil.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'alphabet-e-bisindo',
    word: 'E',
    category: 'alfabet',
    type: 'bisindo',
    description: 'Ujung semua jari ditekuk mendekati telapak, ibu jari sejajar di depan jari.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'alphabet-f-bisindo',
    word: 'F',
    category: 'alfabet',
    type: 'bisindo',
    description: 'Ibu jari dan telunjuk membentuk lingkaran, tiga jari lainnya tegak ke atas.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'number-1-bisindo',
    word: '1',
    category: 'angka',
    type: 'bisindo',
    description: 'Telunjuk tegak ke atas, jari lain menggenggam lembut ke telapak tangan.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'number-2-bisindo',
    word: '2',
    category: 'angka',
    type: 'bisindo',
    description: 'Telunjuk dan jari tengah terbuka membentuk huruf V, jari lain tertutup.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'number-3-bisindo',
    word: '3',
    category: 'angka',
    type: 'bisindo',
    description: 'Ibu jari, telunjuk, dan jari tengah terbuka; dua jari lain menutup ke telapak.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'number-4-bisindo',
    word: '4',
    category: 'angka',
    type: 'bisindo',
    description: 'Empat jari terbuka tegak rapat, ibu jari menekuk ke dalam telapak.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'number-5-bisindo',
    word: '5',
    category: 'angka',
    type: 'bisindo',
    description: 'Semua jari dan ibu jari terbuka lebar dengan telapak menghadap ke depan.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'word-halo-bisindo',
    word: 'Halo',
    category: 'kata_umum',
    type: 'bisindo',
    description: 'Tangan terbuka di dekat pelipis lalu digerakkan kecil ke luar sebagai sapaan ramah.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'word-terima-kasih-bisindo',
    word: 'Terima Kasih',
    category: 'kata_umum',
    type: 'bisindo',
    description: 'Ujung jari tangan dominan menyentuh dagu lalu bergerak ke depan dengan halus.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'word-maaf-bisindo',
    word: 'Maaf',
    category: 'kata_umum',
    type: 'bisindo',
    description: 'Kedua telapak tangan dikepalkan lembut lalu digerakkan melingkar kecil di dada.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'word-tolong-bisindo',
    word: 'Tolong',
    category: 'kata_umum',
    type: 'bisindo',
    description: 'Telapak tangan terbuka diletakkan di depan dada lalu didorong sedikit ke depan.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'word-nama-bisindo',
    word: 'Nama',
    category: 'kata_umum',
    type: 'bisindo',
    description: 'Dua jari telunjuk dan tengah dari kedua tangan saling bersilangan dua kali.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'word-saya-bisindo',
    word: 'Saya',
    category: 'kata_umum',
    type: 'bisindo',
    description: 'Telunjuk tangan dominan menunjuk ringan ke arah dada sendiri.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'word-kamu-bisindo',
    word: 'Kamu',
    category: 'kata_umum',
    type: 'bisindo',
    description: 'Telunjuk diarahkan lembut ke lawan bicara sebagai penanda orang kedua.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'word-makan-bisindo',
    word: 'Makan',
    category: 'kata_umum',
    type: 'bisindo',
    description: 'Ujung jari rapat menyentuh area mulut berulang satu kali seperti gerakan menyuap.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'word-minum-bisindo',
    word: 'Minum',
    category: 'kata_umum',
    type: 'bisindo',
    description: 'Tangan membentuk seolah memegang gelas lalu dimiringkan ke arah mulut.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'phrase-selamat-pagi-bisindo',
    word: 'Selamat Pagi',
    category: 'frasa',
    type: 'bisindo',
    description: 'Gabungan isyarat selamat dan pagi dengan gerakan terbuka dari dada lalu menunjukkan matahari terbit.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'phrase-apa-kabar-bisindo',
    word: 'Apa Kabar',
    category: 'frasa',
    type: 'bisindo',
    description: 'Tangan dominan membentuk isyarat tanya lalu diikuti gerakan kabar di depan dada.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'phrase-sampai-jumpa-bisindo',
    word: 'Sampai Jumpa',
    category: 'frasa',
    type: 'bisindo',
    description: 'Kedua telunjuk diarahkan saling mendekat lalu bergerak menjauh sebagai penanda perpisahan.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'phrase-selamat-malam-bisindo',
    word: 'Selamat Malam',
    category: 'frasa',
    type: 'bisindo',
    description: 'Isyarat selamat dilanjutkan gerakan telapak turun menutup seperti malam datang.',
    imageUrl: '',
    videoUrl: '',
  },
  {
    id: 'phrase-saya-mau-makan-bisindo',
    word: 'Saya Mau Makan',
    category: 'frasa',
    type: 'bisindo',
    description: 'Rangkaian isyarat saya, mau, lalu makan dengan jeda singkat yang jelas di setiap kata.',
    imageUrl: '',
    videoUrl: '',
  },
];

export const dailyWords: string[] = [
  'word-halo-bisindo',
  'word-terima-kasih-bisindo',
  'word-maaf-bisindo',
  'word-tolong-bisindo',
  'word-nama-bisindo',
  'word-saya-bisindo',
  'phrase-apa-kabar-bisindo',
];
